FROM node:18-alpine AS build
WORKDIR /usr/src/app
ENV NODE_ENV=development
COPY package*.json ./
COPY tsconfig.json ./
COPY . .
RUN npm install
RUN npm run build

FROM node:18-alpine AS release
WORKDIR /usr/src/app
ENV NODE_ENV=production
COPY --from=build /usr/src/app/package*.json ./
RUN npm install --omit-dev --ignore-scripts
COPY --from=build /usr/src/app/dist ./dist
CMD [ "node", "dist/index.js" ]