version: "3.8"
services:
  backend:
    container_name: seller-igm-node
    build: .
    ports:
      - "8000:8000"
    restart: always

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - './data:/data/db'
